import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { LoaderCircle, MessageCircle, Plus } from 'lucide-react';
import { createDiscussionReply, createDiscussionThread, loadDiscussionReplies, loadDiscussionThread, loadDiscussionThreads, loadMembershipSession } from '../api/client';
import '../styles/membership.css';

const date = (value) => new Intl.DateTimeFormat('sk-SK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const message = (error) => error?.data?.error === 'discussion_thread_locked' ? 'Táto diskusia je uzamknutá.' : 'Niečo sa nepodarilo. Skúste to, prosím, ešte raz.';

export default function Discussion() {
  const { threadId } = useParams();
  const [access, setAccess] = useState(null); const [threads, setThreads] = useState([]); const [thread, setThread] = useState(null); const [replies, setReplies] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(true); const [title, setTitle] = useState(''); const [body, setBody] = useState('');
  const load = async () => { setBusy(true); setError(''); try { const session = await loadMembershipSession(); setAccess(session?.hasAccess); if (!session?.hasAccess) return; if (threadId) { const [nextThread, nextReplies] = await Promise.all([loadDiscussionThread(threadId), loadDiscussionReplies(threadId)]); setThread(nextThread); setReplies(nextReplies.replies); } else setThreads((await loadDiscussionThreads()).threads); } catch (e) { setError(message(e)); } finally { setBusy(false); } };
  // `load` intentionally closes over the current route and component state.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [threadId]);
  const submit = async (event) => { event.preventDefault(); setError(''); try { if (threadId) { const reply = await createDiscussionReply({ threadId, body }); setReplies((value) => [...value, reply]); setBody(''); } else { const created = await createDiscussionThread({ title, body }); setThreads((value) => [created, ...value]); setTitle(''); setBody(''); } } catch (e) { setError(message(e)); } };
  if (busy) return <main className="membership-page" id="main-content"><div className="membership-feed__loading" role="status"><LoaderCircle className="membership-spinner" />Načítavam diskusiu…</div></main>;
  if (!access) return <main className="membership-page" id="main-content"><section className="membership-empty"><MessageCircle aria-hidden="true" /><h1>Diskusia je pre členov klubu</h1><p>Prihláste sa s aktívnym alebo bezplatným členstvom.</p><Link className="membership-button membership-button--primary" to="/klub/prihlasenie">Prihlásiť sa</Link></section></main>;
  return <main className="membership-page" id="main-content"><section className="membership-discussion"><nav className="membership-club-nav" aria-label="Navigácia klubu"><Link to="/klub">← Späť do Klubu</Link><Link aria-current="page" to="/klub/diskusia">Diskusia</Link></nav>{error && <p className="membership-status" role="alert">{error}</p>}{threadId ? <><Link className="membership-text-button membership-text-button--on-light" to="/klub/diskusia">← Všetky diskusie</Link>{thread && <article className="membership-discussion__thread"><h1>{thread.title}</h1><p className="membership-discussion__meta">{thread.author.displayName} · {date(thread.createdAt)}</p><p>{thread.body}</p></article>}<div className="membership-discussion__replies">{replies.map((reply) => <article key={reply.id}><strong>{reply.author.displayName}</strong><time>{date(reply.createdAt)}</time><p>{reply.body}</p></article>)}</div>{!thread?.isLocked ? <form className="membership-form" onSubmit={submit}><label htmlFor="discussion-reply">Vaša odpoveď</label><textarea id="discussion-reply" value={body} onChange={(e) => setBody(e.target.value)} maxLength="8000" required /><button className="membership-button membership-button--primary">Odpovedať</button></form> : <p>Táto diskusia je uzamknutá.</p>}</> : <><header><h1>Diskusia v klube</h1><p>Bezpečný priestor pre otázky a skúsenosti členov.</p></header><form className="membership-form membership-discussion__form" onSubmit={submit}><label htmlFor="discussion-title">Názov témy</label><input id="discussion-title" value={title} onChange={(e) => setTitle(e.target.value)} maxLength="180" required /><label htmlFor="discussion-body">Text príspevku</label><textarea id="discussion-body" value={body} onChange={(e) => setBody(e.target.value)} maxLength="8000" required /><button className="membership-button membership-button--primary"><Plus aria-hidden="true" size={18}/>Vytvoriť tému</button></form><div className="membership-discussion__list">{threads.length ? threads.map((item) => <Link key={item.id} to={`/klub/diskusia/${item.id}`}><strong>{item.title}</strong><span>{item.author.displayName} · {item.replyCount} odpovedí · {date(item.createdAt)}</span></Link>) : <div className="membership-empty"><h2>Zatiaľ bez tém</h2><p>Začnite prvú konverzáciu.</p></div>}</div></>}</section></main>;
}
